### ISSUE TITLE
fuck off

### ISSUE THREAD

**Issue by WeGoJimmmm** [WeGoJimmmm/Session-4#3]
@SwaradaShirodkar @MANUELGOGIM

**Comment by MANUELGOGIM** [comment]
@SwaradaShirodkar babaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

**Comment by WeGoJimmmm** [comment]
@SwaradaShirodkar botttttt

**Comment by MANUELGOGIM** [comment]
@WeGoJimmmm baba
